### ISSUE TITLE
Racket v8.1 has been released

### ISSUE THREAD

**Issue by evdubs** [takikawa/racket-ppa#12]
Is it helpful or annoying if I submit a new issue when a new release occurs?

**Comment by takikawa** [comment]
Thanks, this is on my TODO list and I expect to have it updated soon. It's fine to make an issue for it, either way fine with me.

**Comment by takikawa** [comment]
PPA packages are now building (https://launchpad.net/~plt/+archive/ubuntu/racket) and will be uploaded soon so I'll close this now
