### ISSUE TITLE
Unable to use PPA (jammy)

### ISSUE THREAD

**Issue by karkeedaniel** [takikawa/racket-ppa#18]
When attempting:

`$ sudo add-apt-repository ppa:plt/racket`

I get:

```
...
Err:9 https://ppa.launchpadcontent.net/plt/racket/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Reading package lists... Done                             
E: The repository 'https://ppa.launchpadcontent.net/plt/racket/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by samth** [comment]
There's no PPA entry for Jammy because it had not been released when the PPA was most recently updated. When 8.5 is added, which should be soon, then it will be available.

**Comment by takikawa** [comment]
A jammy package should be available now (https://launchpad.net/~plt/+archive/ubuntu/racket/+packages). Closing this issue, but let me know if there are any issues.
