### ISSUE TITLE
librktio.a is missing in the racket package

### ISSUE THREAD

**Issue by yangh** [takikawa/racket-ppa#6]
Hi Asumu

I installed racket 7.4 from ppa, and try to build https://gitlab.com/nebogeo/fluxus, which will link to libracket3m.a, I got the following errors:

g++ -o fluxus -rdynamic src/GLEditor.o src/GLFileDialog.o src/Interpreter.o src/Repl.o src/Recorder.o src/FluxusMain.o src/PolyGlyph.o src/Unicode.o src/main.o -L/usr/lib/racket -L/usr/lib -L/usr/lib -L/home/yanghong/workspace/private/libfluxus -lm -lracket3m -lpthread -ldl -ljpeg -ltiff -lfreetype -lz -lbz2 -lpng -lode -lsndfile -lfftw3 -llo -lGLEW -ljack -lGL -lGLU -lglut -lasound -lopenal
/usr/lib/libracket3m.a(network.o): In function `check_lookup':
(.text+0x177): undefined reference to `rktio_poll_addrinfo_lookup_ready'
/usr/lib/libracket3m.a(network.o): In function `connect_cleanup':
(.text+0x209): undefined reference to `rktio_addrinfo_lookup_stop'
(.text+0x248): undefined reference to `rktio_connect_stop'
(.text+0x268): undefined reference to `rktio_addrinfo_free'
(.text+0x288): undefined reference to `rktio_addrinfo_free'
(.text+0x2bb): undefined reference to `rktio_close'
...

It seems that librktio.a is missing, and it's a separate .a file.

I tried to build racket by myself, and:

sudo cp ./racket/src/build/rktio/librktio.a /usr/lib/

And add  -lrktio -lffi to the command line to get fluxus built successfully.

Could you please help to add librktio.a into the package, so that users no need to build racket from the source code to install it.

Thanks
Walter

**Comment by yangh** [comment]
I can see that the librktio.a is not in the racket package:

> dpkg -L racket |grep lib
> 
> /usr/lib
> /usr/lib/libracket3m.a
> /usr/lib/racket
> /usr/lib/racket/buildinfo
> /usr/lib/racket/gracket
> /usr/lib/racket/launchers.rktd
> /usr/lib/racket/mans.rktd
> /usr/lib/racket/mzdyn3m.o
> /usr/lib/racket/starter
> /usr/lib/racket/starter-sh
> /usr/lib/racket/system.rktd

**Comment by takikawa** [comment]
Hi, sorry for the late response, but I did look into this as part of making the v7.6 release for the PPA.

Unfortunately, I don't believe this is a bug with the PPA package. If you build a Racket install from source and then install it to your system unix-style, the Racket build scripts will also not install `librktio.a` as far as I can tell. So I think this issue is better left for upstream rather than in packaging.

**Comment by yangh** [comment]
Hi taki, the v7.6 release works for me, no need to build and copy the librktio.a any more. Thanks for your response.

BR.
